go.property("destroyed", false)

function on_message(self, message_id, message)
	if message_id == hash("trigger_response") then
		if message.other_group == hash("asteroid") then
			msg.post("#sprite", "disable")
			msg.post("#border", "destroyed")
			particlefx.play("#explotion", function()
				msg.post(".", "disable")
				msg.post("/restart#script", "game_over") 
				go.set("#", "destroyed", true)
			end)
		end
	end
end

function on_reload(self)
end
